sudo: false

language: c
compiler:
  - gcc

services:
  - docker

before_install:
  - docker pull ebassi/emeusci

before_script:
  - echo FROM ebassi/emeusci > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t emeusci:withgit .

script:
  - docker run emeusci:withgit /bin/sh -c "cd /root && make V=1 CC=$CC all"
